// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calculation struct {
	ID           int32
	PackSizes    string
	TargetAmount int32
	ResultJson   []byte
	TotalItems   int32
	CreatedAt    pgtype.Timestamp
}
