// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCalculation(ctx context.Context, arg CreateCalculationParams) (Calculation, error)
	ListCalculations(ctx context.Context) ([]Calculation, error)
}

var _ Querier = (*Queries)(nil)
