// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createCalculation = `-- name: CreateCalculation :one
INSERT INTO calculations (
  pack_sizes, target_amount, result_json, total_items
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, pack_sizes, target_amount, result_json, total_items, created_at
`

type CreateCalculationParams struct {
	PackSizes    string
	TargetAmount int32
	ResultJson   []byte
	TotalItems   int32
}

func (q *Queries) CreateCalculation(ctx context.Context, arg CreateCalculationParams) (Calculation, error) {
	row := q.db.QueryRow(ctx, createCalculation,
		arg.PackSizes,
		arg.TargetAmount,
		arg.ResultJson,
		arg.TotalItems,
	)
	var i Calculation
	err := row.Scan(
		&i.ID,
		&i.PackSizes,
		&i.TargetAmount,
		&i.ResultJson,
		&i.TotalItems,
		&i.CreatedAt,
	)
	return i, err
}

const listCalculations = `-- name: ListCalculations :many
SELECT id, pack_sizes, target_amount, result_json, total_items, created_at FROM calculations
ORDER BY created_at DESC
`

func (q *Queries) ListCalculations(ctx context.Context) ([]Calculation, error) {
	rows, err := q.db.Query(ctx, listCalculations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calculation
	for rows.Next() {
		var i Calculation
		if err := rows.Scan(
			&i.ID,
			&i.PackSizes,
			&i.TargetAmount,
			&i.ResultJson,
			&i.TotalItems,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
